openapi: 3.0.3
info:
  title: Product API
  version: 1.0.0
  description: This is the API for Product Service.
servers:
  - url: http://localhost:8080/v1
    description: Development server
tags:
  - name: product
    description: Operations about product
paths:
  /product:
    post:
      tags:
        - product
      summary: Add a new product
      operationId: addProduct
      requestBody:
        description: Product object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        201:
          description: Create successful
          content: { }
        400:
          description: Invalid ID supplied
          content: { }
        404:
          description: Product not found
          content: { }
        405:
          description: Invalid input
          content: { }
      security:
        - product_auth:
            - write:products
            - read:products
  /product/{productId}:
    get:
      tags:
        - product
      summary: Find product by ID
      description: Returns a single product
      operationId: getProductById
      parameters:
        - name: productId
          in: path
          description: ID of Product to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              examples:
                product:
                  $ref: '#/components/examples/Product'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Product not found
          content: {}
      security:
        - api_key: []
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        photoUrls:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: Product Stauts
          enum:
            - normal
            - suspend
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
  examples:
    Category:
      summary: Category data example
      value:
        id: 12345678
        name: clothes
    Tag:
      summary: Tag data example
      value:
        id: 12345678
        type: sports
    Product:
      summary: Product data example
      value:
        id: 12345678
        name: pants
        status: normal
        category:
          $ref: '#/components/examples/Category'
        tag:
          $ref: '#/components/examples/Tag'